#!/bin/bash

# This is the input for parteA of SMCPP.

# DO NOT LEAVE ANY FREE SPACE AFTER THE ARGUMENT. REMEMBER TO LEAVE THE SPACES BETWEEN =

# nucgms .log file
LOG    = res-bhs.log

# nucgms .dat file
DAT    = res-bhs.dat

# CSF's construction type
CSF    = SE

# parteA input spec

%INI_CONTROL_BLOCK
PROJEC = -1  # electron is -1 and postron is +1
NDEBUG = 0  # debug opition
NWHAQQ = 1  #
NRFOCK = 1  #
NTWOEL = 1  #
NROUTE = 0  #
NDSHEL = 5  #
NLIDEP = 0  #
ORBFMT = GAMESS  # bound state calculation software employed
SOLVAT = VACUUM  # solvent
%END_CONTROL_BLOCK


 