#!/bin/bash

# This is the input for off of SMCPP (parteB).

# DO NOT LEAVE ANY FREE SPACE AFTER THE ARGUMENT. REMEMBER TO LEAVE THE SPACES BETWEEN

# CSF's construction type
CSF    = SE

## Control block
%INI_CONTROL_BLOCK 
NDEBUG = 0  #
RUNTYP = OFF  #
KEYDEN = NONE  #
WRTOFF = NDND  #
INVERT = LUF_LPK  #
IN_MEM = DEN  #
NOENER = 1  #
ENERGY =  
 1.0
%END_CONTROL_BLOCK  

## Quadrature for intergration

# Initial and final points of the quadrature
INT_POINT = 1  
END_POINT = 40  

# Spec. of the quadrature
%INI_QUADTRE_BLOCK
QUADT = GAUSS  # Quadrature type
NOTHT = 32  #
NOPHI = 32  #
QUADK = LEGEN  #
KRAD1 = 32  #
KRAD2 = 32  #
XKMAX = 1.6  #
KCALC = SEL  #
%END_QUADTRE_BLOCK