#!/bin/bash

# This script .
# Script made by Ely Miranda, PhD student at Physics Institute in Universidade de São Paulo
# Last update: 06/02/2023
# Any question or suggestion write me: ely.miranda@usp.br :)


### Input important informations

if [ $# -eq 0 ]; then  # If no argument (input) is given, end the script.
    echo "No input provided"
    exit 1
fi

if [ "$1" != "offsmc" ] && [ "$1" != "onksmc" ] && [ "$1" != "3dksmc" ] && [ "$1" != "plotcross" ]; then
  echo "The input provided is not compatible with any script (run or pseudospec)."
  exit 1
fi

$SMC/$1 $2
